image: 
  name: node:14

variables:
    CI_PROJECT_NAME: ydx

stages:
  - deploy
 
cache:
  paths:
    - node_modules/

deploy job:
    only:
        - master
    stage: deploy
    tags:
        - dev
    script:
        - docker build -t "${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-1.${CI_JOB_ID}" .
        - docker stop ${CI_PROJECT_NAME}
        - docker rm ${CI_PROJECT_NAME}
        - docker run -v /mnt/ebs/ydx:/public/audio --name ${CI_PROJECT_NAME} -d -p 0.0.0.0:4000:4000 ${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-1.${CI_JOB_ID}
